[connections.default]
warehouse = "QUICKSTART_WH"
role = "ACCOUNTADMIN"
database = "QUICKSTART_COMMON"
schema = "PUBLIC"
account = "HAYFIN-AZUK"
user = "SVC_DEV"
private_key = ".snowflake/snowflake_rsa_key"
